server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.11.10:3306/test?useSSL=false&characterEncoding=utf8
    username: homestead
    password: secret
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
  freemarker:
    charset: utf-8
    content-type: text/html
