server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.11.10:3306/test?useSSL=false&characterEncoding=utf8
    username: homestead
    password: secret
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
  freemarker:
    charset: utf-8
    content-type: text/html
  output:
    ansi:
      enabled: detect
  devtools:
    restart:
      enabled: true


home:
  province: hubei
  city: wuhan
  desc: ${home.province} ${home.city} different every day ${random.uuid}

logging:
  file: spring-boot.log
  path: /tmp
